[package]
name = "command-pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
tokio = { version = "1.38.0", features = ["full"] }
humantime = "2.1.0"
